# .github/workflows/deploy.yml

name: EC2로 자동배포하기

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 가져오기
        uses: actions/checkout@v4

      - name: Node 설치
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 의존성(라이브러리) 설치
        run: npm ci

      - name: .env 파일 생성
        run: echo "${{ secrets.ENV }}" > .env

      - name: 빌드
        run: npm run build

      - name: 압축
        # NODE_MODULES 폴더는 압축하지 않는다.
        run: tar -czvf codeit-fesi9-aws.tar.gz .next .env package.json package-lock.json

      - name: SCP로 EC2로 빌드된 파일을 전송한다.
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          source: codeit-fesi9-aws.tar.gz
          target: /home/ubuntu/codeit-fesi9-aws/build

      - name: SSH로 EC2 접속하기
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          script: |
            set -e
            rm -rf /home/ubuntu/codeit-fesi9-aws/current
            mkdir /home/ubuntu/codeit-fesi9-aws/current
            mv /home/ubuntu/codeit-fesi9-aws/build/codeit-fesi9-aws.tar.gz /home/ubuntu/codeit-fesi9-aws/current/codeit-fesi9-aws.tar.gz
            cd /home/ubuntu/codeit-fesi9-aws/current
            tar -xvf codeit-fesi9-aws.tar.gz
            npm install
            pm2 kill
            pm2 start npm --name "nextjs-app" -- start
